### ISSUE TITLE
Geomap feature popup not properly rendered in mobile mode

### ISSUE THREAD

**Issue by jvanulde** [wet-boew/wet-boew#2742]
Popup box is resized incorrectly. @jolevesq consider jQuery mobile popups.
![screen shot 2013-07-30 at 12 10 08 pm](https://f.cloud.github.com/assets/2255248/881302/e0b3c72a-f94b-11e2-96e7-d57c4300f638.png)

**Comment by hsrudnicki** [comment]
@jsmoreau  @pjackson28 @LaurentGoderre @jvanulde : can be this issue closed ?

**Comment by jvanulde** [comment]
@hsrudnicki this is still an issue that needs to be resolved.

**Comment by hsrudnicki** [comment]
Again, please update this issue's status [note: there are more related and later created issues of Geomap]

**Comment by jvanulde** [comment]
It's still an issue that needs to be resolved.

**Comment by hsrudnicki** [comment]
again, if this issue has been resolved, then this issue can be closed unless otherwise, please update this issue's status

**Comment by jvanulde** [comment]
Still an issue on small screens.

**Comment by RobJohnston** [comment]
Just took a look at the [projects map page for actionplan.gc.ca](http://www.actionplan.gc.ca/en/projects-map) (take a look quick before it disappears with the new government!).  They've changed it to make it more mobile friendly with the use of [Leaflet](http://leafletjs.com/).  

Leaflet is "an open-source JavaScript library for mobile-friendly interactive maps", and only 33 KB.

Maybe that's the way to resolve this pop-up issue?

**Comment by jvanulde** [comment]
Thanks @RobJohnston for the link. We have much experience with Leaflet and it was considered for Geomap early on in our design process, but it isn't flexible enough for our needs. This particular issue is not a problem with OpenLayers per se, rather it is an implementation issue for which a solution exists. It's lower on the list of priorities right now. We are moving to OpenLayers 3 now anyways. If we wanted to limit the functionality of OL to what is provided by Leaflet we could get the download size much much smaller.

**Comment by hsrudnicki** [comment]
Based on last comment, this issue in regards to resizing can be closed when the functionality of OpenLayers will be limited to what is provided by Leaflet, as well please continue updating of this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue? Either way, please update this issue's status, whether this issue of 2013 can be closed as resolved/fixed or if otherwise? Thank you

**Comment by hsrudnicki** [comment]
Please update this issue's status/milestone for this year as well, thank you

**Comment by jvanulde** [comment]
This issue has been addressed in the latest version Geomap using OpenLayers 3. However, testing will need to confirm if it meets user requirements. Here is a screenshot of what it looks like now:

<img width="414" alt="screen shot 2016-08-10 at 6 55 42 am" src="https://cloud.githubusercontent.com/assets/2255248/17556335/deb5cd62-5ec7-11e6-9196-939b5f9f4b35.png">

When implementing popups one has to take into account the limited space afforded by some devices and adjust the content accordingly.

**Comment by LaurentGoderre** [comment]
@jvanulde can we close and let other open a new issue if a specific problem remains?

**Comment by jvanulde** [comment]
Yes please close. The new version of Geomap is undergoing final accessibility testing.
