### ISSUE TITLE
New download structure for v4.0.16

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/wet-boew#6977]
Since we have the cdn aspect now in 4.0.16, I propose we  switch the downloasd section to the following:

![cdnrelease](https://cloud.githubusercontent.com/assets/1090826/8877992/8858f510-31f6-11e5-8521-6b4a0ecd5d31.PNG)

``` html
<table class="table table-bordered mrgn-bttm-xl">
<thead>
<tr>
<td></td>
<th scope="col">Source code</th>
<th scope="col">Production files</th>
<th scope="col">CDN files</th>
</tr>
</thead>
<tbody>
<tr>
<th>Web Experience Toolkit (WET) Core</th>
<td rowspan="2"><a href="https://github.com/wet-boew/wet-boew/archive/v4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 source code - Web Experience Toolkit (WET) theme</span></a></td>
<td rowspan="2"><a href="https://github.com/wet-boew/wet-boew/releases/download/v4.0.16/wet-boew-dist-4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 production files - Web Experience Toolkit (WET) theme</span></a></td>
<td><a href="https://github.com/wet-boew/wet-boew/releases/download/v4.0.16/wet-boew-cdn-4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 cdn files - Web Experience Toolkit (WET) core</span></a></td>
</tr>
<tr>
<th>Web Experience Toolkit (WET) Theme</th>
    <td><a href="https://github.com/wet-boew/wet-boew/releases/download/v4.0.16/themes-cdn-4.0.16-theme-wet-boew.zip">Download</a></td>
</tr>
<tr>
<th>Base Theme</th>
<td><a href="https://github.com/wet-boew/theme-base/archive/v4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 source code- Base theme</span> (theme only)</a></td>
<td><a href="https://github.com/wet-boew/theme-base/releases/download/v4.0.16/themes-dist-4.0.16-theme-base.zip">Download<span class="wb-inv"> - v4.0.16 production files - Base theme</span></a></td>
    <td><a href="https://github.com/wet-boew/theme-base/releases/download/v4.0.16/themes-cdn-4.0.16-theme-base.zip">Download<span class="wb-inv"> - v4.0.16 cdn files - Base theme</span></a></td>
</tr>
<tr>
<th>Canada.ca Theme</th>
<td><a href="https://github.com/wet-boew/GCWeb/archive/v4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 source code - Canada.ca theme</span> (theme only)</a></td>
<td><a href="https://github.com/wet-boew/GCWeb/releases/download/v4.0.16/themes-dist-4.0.16-gcweb.zip">Download<span class="wb-inv"> - v4.0.16 production files - Canada.ca theme</span></a></td>
    <td><a href="https://github.com/wet-boew/GCWeb/releases/download/v4.0.16/themes-cdn-4.0.16-gcweb.zip">Download<span class="wb-inv"> - v4.0.16 cdn files - Canada.ca theme</span></a></td>
</tr>
<tr>
<th>Government of Canada Web Usability Theme</th>
<td><a href="https://github.com/wet-boew/theme-gcwu-fegc/archive/v4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 source code - Government of Canada Web Usability theme</span> (theme only)</a></td>
<td><a href="https://github.com/wet-boew/theme-gcwu-fegc/releases/download/v4.0.16/themes-dist-4.0.16-theme-gcwu-fegc.zip">Download<span class="wb-inv"> - v4.0.16 production files - Government of Canada Web Usability theme</span></a></td>
<td><a href="https://github.com/wet-boew/theme-gcwu-fegc/releases/download/v4.0.16/themes-cdn-4.0.16-theme-gcwu-fegc.zip">Download<span class="wb-inv"> - v4.0.16 cdn files - Government of Canada Web Usability theme</span></a></td>
</tr>
<tr>
<th>Government of Canada Intranet Theme</th>
<td><a href="https://github.com/wet-boew/theme-gc-intranet/archive/v4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 source code - Government of Canada Intranet theme</span> (theme only)</a></td>
<td><a href="https://github.com/wet-boew/theme-gc-intranet/releases/download/v4.0.16/themes-dist-4.0.16-theme-gc-intranet.zip">Download<span class="wb-inv"> - v4.0.16 production files - Government of Canada Intranet theme</span></a></td>
<td><a href="https://github.com/wet-boew/theme-gc-intranet/releases/download/v4.0.16/themes-cdn-4.0.16-theme-gc-intranet.zip">Download<span class="wb-inv"> - v4.0.16 cdn files - Government of Canada Intranet theme</span></a></td>
</tr>
<tr>
<th>Open Government Platform (OGPL) Theme</th>
<td><a href="https://github.com/wet-boew/theme-ogpl/archive/v4.0.16.zip">Download<span class="wb-inv"> - v4.0.16 source code - Open Government Platform (OGPL) theme</span> (theme only)</a></td>
<td><a href="https://github.com/wet-boew/theme-ogpl/releases/download/v4.0.16/themes-dist-4.0.16-theme-ogpl.zip">Download<span class="wb-inv"> - v4.0.16 production files - Open Government Platform (OGPL) theme</span></a></td>
<td><a href="https://github.com/wet-boew/theme-ogpl/releases/download/v4.0.16/themes-dist-4.0.16-theme-ogpl.zip">Download<span class="wb-inv"> - v4.0.16 cdn files - Open Government Platform (OGPL) theme</span></a></td>
</tr>
</tbody>
</table>
```

**Comment by pjackson28** [comment]
Do all the theme CDN packages include WET core? The way you have it setup makes it seem like they don't and that core needs to be downloaded separately from the themes. If the themes do have core, then you should do something like adding "(+ WET core)" or something similar to the first column.

**Comment by LaurentGoderre** [comment]
In the CDN version they do not have core no.

**Comment by pjackson28** [comment]
Why wouldn't we bundle core into the theme CDN files, especially now that the theme.min.css is supposed to include both core and them? They should grab just one CDN package and not have to worry about core.

Also what about production files? It is now unclear whether core is included in them as well.

**Comment by LaurentGoderre** [comment]
Please keep in mind the intended audience of the CDN files. The packages should no overlap whatsoever therefore not include core.

**Comment by pjackson28** [comment]
They do overlap now though, theme.min.css = core + theme since you merged the two together. Why would we exclude the rest of core if some of core is already included by default?

What I'm pointing out is it is really confusing as to what is included and what is not. People up until now have just grabbed one package for deploying, now you are making it so they have to grab two for CDN but not making it clear when one or both are needed.

I'm also unclear as to what scenario that they would need to just grab the theme CDN package and not the core CDN package. Where would they not need the core JS for CDN deployment?

**Comment by LaurentGoderre** [comment]
For the majority of people this doesn't affect them, they still download the production files for the theme they are using, just like they did before.

The CDN file are useful for the Drupal variant for example, because it can download core, then only the themes it wants to support. This simplifies their packaging and speed it up because there is no duplication of files.

**Comment by LaurentGoderre** [comment]
Also, if you were to make a CDN, you would get all the CDN packages and extract them in the same location, again with no duplication.

**Comment by nschonni** [comment]
FYI, i'm doing the separation of concerns with the NuGet stuff aswell (#2002). 
EX:
- WET-BEOW.Core only has the base CSS/JS
- WET-BOEW.Theme.WET-BOEW has the them CSS/JS/Assets and depends on the Core package

**Comment by pjackson28** [comment]
Then it will need to be made clear in the proposed download what is and isn't included. With your new approach, it makes it look like you split out core from production as well. All I'm suggesting is being clearer as to what does and doesn't include core. The proposed approach is easy to misinterpret. Perhaps be clear that production files include core while CDN files do not.

**Comment by LaurentGoderre** [comment]
What is your suggestion then?

**Comment by pjackson28** [comment]
Maybe state it in the Production and CDN column headings that they include/don't include core.

**Comment by nschonni** [comment]
@LaurentGoderre I guess this sample psuedo footerresources.hbs is what you're thinking the people would use?
```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/{{environment.jqueryVersion}}/jquery.js"></script>
<script src="{{core-cdn}}/js/wet-boew.js"></script>
<!--<![endif]-->
{{#if page.js}}{{#each page.js}}<script src="{{this}}.js"></script>{{/each}}{{/if}}
{{#if page.jsie9}}
<!--[if lte IE 9]>
{{#each page.jsie9}}<script src="{{this}}.js"></script>{{/each}}
<![endif]-->
{{/if}}
<!--[if lt IE 9]>
<script src={{core-cdn}}/js/ie8-wet-boew2.js"></script>
{{#if page.jsie8}}{{#each page.jsie8}}<script src="{{this}}.js"></script>{{/each}}{{/if}}
<![endif]-->
{{#if site.themeJS}}
<script src="{{theme-cdn}}/{{site.theme}}/js/theme.js"></script>
{{/if}}
```

**Comment by LaurentGoderre** [comment]
Close, but tt would be more like this:

```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/{{environment.jqueryVersion}}/jquery.js"></script>
<script src="{{cdn}}/wet-boew/js/wet-boew.js"></script>
<!--<![endif]-->
{{#if page.js}}{{#each page.js}}<script src="{{this}}.js"></script>{{/each}}{{/if}}
{{#if page.jsie9}}
<!--[if lte IE 9]>
{{#each page.jsie9}}<script src="{{this}}.js"></script>{{/each}}
<![endif]-->
{{/if}}
<!--[if lt IE 9]>
<script src={{cdn}}/wet-boew/js/ie8-wet-boew2.js"></script>
{{#if page.jsie8}}{{#each page.jsie8}}<script src="{{this}}.js"></script>{{/each}}{{/if}}
<![endif]-->
{{#if site.themeJS}}
<script src="{{tcdn}}/{{site.theme}}/js/theme.js"></script>
{{/if}}
```

They have to reside at the same place because of some assets.

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise?

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed or otherwise?

**Comment by hsrudnicki** [comment]
Based on the above, this issue has been resolved/fixed, so it can be closed unless you think otherwise?
Please update this issue's status, thx

**Comment by LaurentGoderre** [comment]
No, this was not resolved. People have no idea they can download the cdn version

**Comment by hsrudnicki** [comment]
As well this issue, in regards to CDN, needs a status update again unless otherwise?

**Comment by hsrudnicki** [comment]
Is this still a valid issue? Please update the status of this for the current year, thank you

**Comment by masterbee** [comment]
Closed since caller (creator of issue) has abandoned the issue.
