### ISSUE TITLE
Is it possible to animate a modal dialog/overlay upon opening/closing?

### ISSUE THREAD

**Issue by charlesmorin** [wet-boew/wet-boew#7101]
Question says it all.

If not, do you have a recommendation in terms of accessibility or UX? I have to display a "Loading in progress" message during an AJAX call in a Java EE application. It must be modal so I thought the overlay would do the work. It needs to be invoked from JavaScript (callbacks from the AJAX call).

Also, following the documentation, I cannot display the modal dialog from JavaScript. Nothing happens.
http://wet-boew.github.io/v4.0-ci/docs/ref/overlay/overlay-en.html

> $( "#unique-id" ).trigger( "open.wb-overlay" );

Thank you

Charles

**Comment by hsrudnicki** [comment]
@charlesmorin : Please update this issue status whether this issue can be closed or otherwise? @pjackson28 @LaurentGoderre and others: when applicable, please help in solving and closing this issue, thank you all

**Comment by charlesmorin** [comment]
I did not have any response so I can't tell you that it is fixed or not.

Thank you

**Comment by andre-gh** [comment]
Could you verify you attempted to trigger open on the section element of the overlay?

**Comment by hsrudnicki** [comment]
@charlesmorin: Is your question, in regards to applying of event approach to trigger the overlay as a loading message during Ajax call, still an issue or if otherwise?   Either way, please update this issue's status, whether this issue, lingering for 4-5 months, can be closed as resolved/fixed or otherwise? Thank you

**Comment by charlesmorin** [comment]
@andre-gh Yes I did trigger open on the section element. What I am looking for is to make it prettier using an animation (animate from jQuery). 

@hsrudnicki Yes, you can close the ticket since it looks like it is not supported by the current version of WET4. Thank you.

**Comment by hsrudnicki** [comment]
@masterbee / @LaurentGoderre : This issue can be closed based on the last comment unless you think otherwise, please update this, thank you
