### ISSUE TITLE
Collapsible alerts is hugely inconsistant between open and closed states

### ISSUE THREAD

**Issue by andre-gh** [wet-boew/wet-boew#7137]
Related to #6991

When open the details has a rounded border, squared border when closed

When closed the details has a left hand thick border, that border is gone when closed

The summary text border changes in various ways between open and closed

There is a thing gray border around the details when open, gone when closed

Open: 
![ff](https://cloud.githubusercontent.com/assets/13316676/10289704/bd540a24-6b6d-11e5-8c42-405f749cc5d9.png)

Closed: 
![ff](https://cloud.githubusercontent.com/assets/13316676/10289718/cd7018d0-6b6d-11e5-8524-9e0421a06e46.png)

**Comment by andre-gh** [comment]
@LaurentGoderre Is this fixed by your PR?

**Comment by pjackson28** [comment]
@Pacoup Bridging you in.

**Comment by LaurentGoderre** [comment]
That would have been fixed by my PR but now you have to fix it manually

**Comment by andre-gh** [comment]
I closed your PR understanding that this would occur, no worries.  These workarounds are temporary fixes until we can address the issue properly in 4.1

**Comment by hsrudnicki** [comment]
Based on the last comment, this issue remains as opened, and this issue's status will be updated in the 4.1 [unless otherwise? So please update it when applicable, thx]
