### ISSUE TITLE
Feeds plugin won't work

### ISSUE THREAD

**Issue by Belange87** [wet-boew/wet-boew#7243]
Hi, do you have any ideas why the FEEDS plugin v3.1 is not showing result.

**Comment by LaurentGoderre** [comment]
Because the third party service used has been deprecated. WET4 was using it but it has been fixed in the latest version

**Comment by afull** [comment]
We have updated WET4 to version wet-boew-dist-4.0.19-2 on our development servers.
I am still unable to get our RSS Feeds to display.

http://news.gc.ca/web/fd-en.do?mthd=dpt&ft=atom&crtr.dpt1D=6672

Was there some additional change in the code that I am missing.

<section class="wb-feeds limit-5">
	<h3>ENVIRONMENT CANADA</h3>
	<ul class="feeds-cont">
		<li>
			<a href="http://news.gc.ca/web/fd-en.do?mthd=dpt&ft=atom&crtr.dpt1D=6672" rel="external">EC News</a>
		</li>
	</ul>
</section>

**Comment by LaurentGoderre** [comment]
@andre-gh

**Comment by Belange87** [comment]
Do you have any ideas what is the problem so we can try to fix it ?

**Comment by pjackson28** [comment]
@Belange87 The Google feeds API service that the plugin was dependent upon has been discontinued. Pretty much the plugin has to be rebuilt to use another service (in v4 we are now using YQL).

Note that support for WET v3.1 was discontinued over a year ago (in September 2014) and there have been no fixes to any of the v3.1 issues since that point (and there won't be any going forward). We highly recommend that you migrate to WET v4.0 which is actively supported and has this feeds issue already fixed.

**Comment by tabouziane** [comment]
I'm working at Global Affairs Canada and I found a way to solve this issue using YQL. It's working pretty well! See it in action here: http://www.international.gc.ca/media/index.aspx?lang=eng
Note that I didn’t make the changes in the WET js files, since I don’t have access to them:
• js/workers/webwidget.js
• js/sass/webwidget.scss
• js/images/webfeeds/

Here's the code:

<script type="text/javascript"> 
	function injectScript(url) { 
	var scriptElement = document.createElement('script'); 
	scriptElement.setAttribute('type', 'text/javascript'); 
	scriptElement.setAttribute('src', url); 
	document.getElementsByTagName('head')[0].appendChild(scriptElement); 
	} 
	function handleResponse(response) { 
	//console.log(response); 
	var text = '', 
	item; 
	//response.query.results.feed.entry.length 
	for (var i = 0, k = NUMBER_OF_NEWS_YOU_WANT_TO_DISPLAY; i < k; i++) { 
	item = response.query.results.feed.entry[i]; 
	item.date = item.date.substring(0, 10); 
	text += '<li><a href="' + item.link.href + '">' + item.title + '</a><br/>' + item.date +'</li>'; 
	} 
	document.getElementById('news-feed-wet').innerHTML = text; 
	} 
	document.addEventListener("DOMContentLoaded", function() { 
	// https://developer.yahoo.com/yql/console/ 
	// select * from feednormalizer where url='http://news.ycombinator.com/rss' and output='atom_1.0' 
	injectScript("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20feednormalizer%20where%20url%3D'ADD_YOUR_XML_URL_HERE'%20and%20output%3D'atom_1.0'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=handleResponse"); 
	}, false ); 
	</script>

Two things you need to change on the script:

1. Change the number of items you want to display, if you want to display all your news, change:

k = NUMBER_OF_NEWS_YOU_WANT_TO_DISPLAY to k = response.query.results.feed.entry.length <

2. Add your XML URL using the YQL Convert to JSON or XML here - https://developer.yahoo.com/yql/ 

On the page you want the news feed to show add this:

<div class="span-6 module-related">
<ul class="widget-content" id="news-feed-wet">
<li><a href="LINK_TO_ALL_YOUR_NEWS_ON_NEWS.GC.CA">DEPARTMENT_NAME News</a></li>
</ul>
</div>
<p class="align-right"><a href="LINK_TO_ALL_YOUR_NEWS_ON_NEWS.GC.CA">More...</a></p>
</div>

If you have any questions/comments feel free to contact me.

Hope this helps,

Best,

Tarik
tarik.abouziane@international.gc.ca

**Comment by tabouziane** [comment]
Sorry for the spam but I forgot to add the markdown for code. So here it is -

Script

```
<script type="text/javascript"> 
	function injectScript(url) { 
	var scriptElement = document.createElement('script'); 
	scriptElement.setAttribute('type', 'text/javascript'); 
	scriptElement.setAttribute('src', url); 
	document.getElementsByTagName('head')[0].appendChild(scriptElement); 
	} 
	function handleResponse(response) { 
	//console.log(response); 
	var text = '', 
	item; 
	//response.query.results.feed.entry.length 
	for (var i = 0, k = NUMBER_OF_NEWS_YOU_WANT_TO_DISPLAY; i < k; i++) { 
	item = response.query.results.feed.entry[i]; 
	item.date = item.date.substring(0, 10); 
	text += '<li><a href="' + item.link.href + '">' + item.title + '</a><br/>' + item.date +'</li>'; 
	} 
	document.getElementById('news-feed-wet').innerHTML = text; 
	} 
	document.addEventListener("DOMContentLoaded", function() { 
	// https://developer.yahoo.com/yql/console/ 
	// select * from feednormalizer where url='http://news.ycombinator.com/rss' and output='atom_1.0' 
	injectScript("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20feednormalizer%20where%20url%3D'ADD_YOUR_XML_URL_HERE'%20and%20output%3D'atom_1.0'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=handleResponse"); 
	}, false ); 
	</script>

```


In the page: 

```
<div class="span-6 module-related">
<ul class="widget-content" id="news-feed-wet">
<li><a href="LINK_TO_ALL_YOUR_NEWS">DEPARTMENT_NAME News</a></li>
</ul>
</div>
<p class="align-right"><a href="LINK_TO_ALL_YOUR_NEWS">More...</a></p>
</div>

```

Again if you need help let me know.

Tarik
tarik.abouziane@international.gc.ca

**Comment by hsrudnicki** [comment]
@Belange87 and others: Based on the last comment(s), can be this issue closed as resolved/fixed or if otherwise?  
Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?   Thank you

**Comment by hsrudnicki** [comment]
Added "Going Stale" label, and to keep this issue opened, please update this issue's status, thank you
