### ISSUE TITLE
Form validation styles for horizontal form

### ISSUE THREAD

**Issue by biljanap** [wet-boew/wet-boew#7284]
WET4 does not seem to provide styles for horizontal form where there are required fields present.
This is what I get if I make e-mail field required.
![form-valid-horizontal](https://cloud.githubusercontent.com/assets/2146304/11669847/d64c0072-9dcc-11e5-930c-50748236bd76.jpg)

Here is the code:
```html
<form class="form-horizontal" action="#" method="get" id="validation-example">
      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label required">Email <strong class="required">(required)</strong></label></label>
        <div class="col-sm-10">
          <input type="email" class="form-control" id="inputEmail3" placeholder="Email" required />
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Sign in</button>
        </div>
      </div>
</form>
```
We are using horizontal forms for our web application because they can be very long. I can always create custom css but I would rather use WET4 styles if available. Is there anything I can use?

**Comment by RobJohnston** [comment]
:+1:

**Comment by hsrudnicki** [comment]
In the meantime, either way if it's still an issue, waiting for a css fix/resolution or if otherwise, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise, thank you

**Comment by hsrudnicki** [comment]
Can be this closed or otherwise? Please update the status of this for the current year, thx

**Comment by kpduncan** [comment]
I was able to get this results [IMAGE](https://drive.google.com/open?id=0B8gAdPVo-qRNdFNYQmNrN3p3Tnc)

This is my code:

```html
<div class="wb-frmvld" id="wb-auto-1">
<form class="form-horizontal" action="" method="post" novalidate="novalidate">

<div class="form-group input-left">
<label for="email" class="required" aria-required="true">
<span class="field-name mrgn-rght-sm">Email</span>
<strong class="required mrgn-rght-sm" aria-required="true">(required)</strong>
</label>
<input id="email" class="form-control" type="text" name="email" placeholder="Email" required="required" aria-required="true">
</div>

<div class="form-group">
<button class="btn btn-md btn-success" type="submit" role="button">Submit</button>
</div>

</form>
</div>
```

```css
.input-left label {
	display: flex;
}

.input-left .field-name,.input-left .required {
	float: left;
}

.input-left input {
	float: left;
}
```

**Comment by hsrudnicki** [comment]
So, is this still an open issue or otherwise?  Please update the status of this again, whether this can be closed as resolved, thank you

**Comment by biljanap** [comment]
It looks like this has been fixed for  v.4.0.21. Thanks.

**Comment by cybersubtype** [comment]
I'm using Government of Canada Intranet Theme with `theme.min.css` (v4.0.22 - 2016-08-11) and this does not fix the issue of the horizontal forms. There is a new version (v4.0.23-development - 2016-09-27) just updated yesterday that will fix the issue. But you can't download it from here: http://wet-boew.github.io/wet-boew/docs/versions/dwnld-en.html as of yet. To get the latest version simplest way is to view source on the demo theme pack desired.
