### ISSUE TITLE
Pie chart - 

### ISSUE THREAD

**Issue by agagnon** [wet-boew/wet-boew#9583]
When using attribute "reversettblparsing": true and the pie Chart, there is a bug where the "subtitle" is the first category instead of the data column header. In the image below, you can see that the subtitle above the chart is "General", and it should be "Task". 
https://wet-boew.github.io/v4.0-ci/demos/charts/testing-en.html

![image](https://github.com/wet-boew/wet-boew/assets/1794026/ea2a39ed-2cf1-4dc6-9aab-9a66c189e568)

**Comment by wewhite** [comment]
The above commit should fix this.
<img width="864" alt="Screenshot 2023-05-10 at 2 07 29 PM" src="https://github.com/wet-boew/wet-boew/assets/111083379/2ac63591-1623-40b6-a6d7-07c77d16d720">

**Comment by EricDunsworth** [comment]
@wewhite Feel free to send over a pull request too 👍!

**Comment by agagnon** [comment]
Is it possible this change has not been  merged somewhere? I just downloaded the new 13.2.1 release of GCWeb and I still have the problem.

**Comment by EricDunsworth** [comment]
@agagnon It looks like #9586 (@wewhite's pull request) is still currently open. So the fix won't "land" in WET/GCWeb until after that PR gets reviewed and merged.
